
--member테이블 생성
CREATE TABLE MEMBER(
    ID VARCHAR2(30) CONSTRAINT PK_MEMBER_ID PRIMARY KEY,
    PASSWORD VARCHAR2(20) CONSTRAINT NN_MEMBER_PASSWORD NOT NULL,
    NAME VARCHAR2(30) CONSTRAINT NN_MEMBER_NAME NOT NULL,
    GENDER VARCHAR2(3) CONSTRAINT CK_MEMBER_GENDER CHECK(GENDER IN('남','여')),
    EMAIL VARCHAR2(40) CONSTRAINT NN_MEMBER_EMAIL NOT NULL,
    PHONE VARCHAR2(14),
    ADDRESS VARCHAR2(200) CONSTRAINT NN_MEMBER_ADD NOT NULL,
    BIRTH VARCHAR2(20),
    REGDATE DATE DEFAULT SYSDATE,
    U_DELETE VARCHAR2(1) DEFAULT 'N' CONSTRAINT CK_MEMBER_U_DELETE CHECK(U_DELETE IN('Y','N')),
    DELDATE DATE DEFAULT SYSDATE,
    GRADE VARCHAR2(10)
);

drop table member;


insert into member(ID,PASSWORD,NAME,GENDER,EMAIL,PHONE,ADDRESS,BIRTH,REGDATE,U_DELETE,DELDATE,GRADE)
values ('admin','1234','웰컴','남','admin@naver.com','01000000000','서울시 구로구 구로동 경영기술원','1995/12/01',sysdate,'N',SYSDATE,'admin');
insert into member(ID,PASSWORD,NAME,GENDER,EMAIL,PHONE,ADDRESS,BIRTH,REGDATE,U_DELETE,DELDATE,GRADE)
values ('hid','1234','홍길동','남','hid@nate.com','01012345678','서울시 구로구 구로동','1993/01/05',sysdate,'N',SYSDATE,'');
insert into member(ID,PASSWORD,NAME,GENDER,EMAIL,PHONE,ADDRESS,BIRTH,REGDATE,U_DELETE,DELDATE,GRADE)
values ('lid','1234','세종대왕','남','lid@nate.com','01045671234','서울시 구로구 신도림동 ','1990/10/10',sysdate,'N',SYSDATE,'bronze');
insert into member(ID,PASSWORD,NAME,GENDER,EMAIL,PHONE,ADDRESS,BIRTH,REGDATE,U_DELETE,DELDATE,GRADE)
values ('did','1234','둘리','남','did@naver.com','01067891234','서울시 구로구 가리봉동 ','2002/09/20',sysdate,'N',SYSDATE,'gold');

select *
from member;

commit;

--product테이블생성
CREATE TABLE PRODUCT(
    P_NO NUMBER(3) CONSTRAINT PK_PRODUCT_P_NO PRIMARY KEY,
    T_NO NUMBER(1) CONSTRAINT FK_PRODUCT_T_NO REFERENCES TYPES(T_NO), 
    P_NAME VARCHAR2(100) CONSTRAINT NN_PRODUCT_P_NAME NOT NULL,
    P_PRICE NUMBER(8) CONSTRAINT NN_PRODUCT_P_PRICE NOT NULL,
    INFO VARCHAR2(1000)
);

SELECT *
FROM PRODUCT;

DROP TABLE PRODUCT;

--REVIEW테이블생성
CREATE TABLE REVIEW (
    R_NO NUMBER(3) CONSTRAINT PK_REVIEW_R_NO PRIMARY KEY,
    ID VARCHAR2(30) CONSTRAINT FK_REVIEW_ID REFERENCES MEMBER(ID),
    P_NO NUMBER(3) CONSTRAINT FK_REVIEW_P_NO REFERENCES PRODUCT(P_NO),
    R_TITLE VARCHAR2(100) CONSTRAINT NN_REVIEW_R_TITLE NOT NULL,
    R_CONTENT VARCHAR2(1000) NOT NULL,
    R_REGDATE DATE DEFAULT SYSDATE,
    R_HIT NUMBER(4),
    R_DELETE VARCHAR2(1) DEFAULT 'N' CONSTRAINT CK_REVIEW_R_DELETE CHECK (R_DELETE IN ('Y','N'))
);

select * 
from review;

drop table REVIEW;

--용도별 테이블생성
CREATE TABLE TYPES (
    T_NO NUMBER(1) CONSTRAINT PK_TYPES_T_NO PRIMARY KEY,
    T_NAME VARCHAR2(30) CONSTRAINT NN_TYTPES_T_NAME NOT NULL
);


DROP TABLE TYPES;

INSERT INTO TYPES(T_NO,T_NAME)
VALUES(1,'사무용');
INSERT INTO TYPES(T_NO,T_NAME)
VALUES(2,'게임용');
INSERT INTO TYPES(T_NO,T_NAME)
VALUES(3,'그래픽디자인용');
INSERT INTO TYPES(T_NO,T_NAME)
VALUES(4,'영상편집');
INSERT INTO TYPES (T_NO,T_NAME)
VALUES(5,'코딩용');

SELECT *
FROM TYPES;
--테스트
CREATE SEQUENCE NO
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

drop sequence no;




--시퀀스 생성 후기게시판에 후기번호에 쓸 시퀀스
CREATE SEQUENCE RNO
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

DROP SEQUENCE RNO;

--시퀀스 생성 문의게시판에 후기번호에 쓸 시퀀스
CREATE SEQUENCE QNO
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

DROP SEQUENCE QNO;


--P_NO 시퀀스 생성
CREATE SEQUENCE P_CODE
START WITH 100
INCREMENT BY 10
NOCYCLE;

DROP SEQUENCE P_CODE;

--QUESTION테이블생성
CREATE TABLE QUESTION (
    Q_NO NUMBER(3) CONSTRAINT PK_QUESTION_Q_NO PRIMARY KEY,
    ID VARCHAR2(30) CONSTRAINT FK_QUESTION_ID REFERENCES MEMBER(ID),
    P_NO NUMBER(3) CONSTRAINT FK_QUESTION_P_NO REFERENCES PRODUCT(P_NO),
    Q_TITLE VARCHAR2(100) CONSTRAINT NN_QUESTION_Q_TITLE NOT NULL,
    Q_CONTENT VARCHAR2(1000) NOT NULL,
    Q_REGDATE DATE DEFAULT SYSDATE,
    Q_HIT NUMBER(4),
    Q_DELETE VARCHAR2(1) DEFAULT 'N' CONSTRAINT CK_QUESTION_Q_DELETE CHECK (Q_DELETE IN ('Y','N'))
);

drop table QUESTION;

CREATE TABLE ANSWER(
    A_NO NUMBER(3) CONSTRAINT FK_ANSWER_A_NO REFERENCES QUESTION(Q_NO),
    ID VARCHAR2(30) CONSTRAINT FK_ANSWER_ID REFERENCES MEMBER(ID),
    A_CONTNENT VARCHAR2(1000) not null,
    A_REGDATE DATE,
    A_DELETE VARCHAR2(1) DEFAULT 'N' CONSTRAINT CK_A_COMMENT_A_DELETE CHECK (A_DELETE IN ('Y','N'))
    );

DROP TABLE ANSWER;